// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxuvtnnulydrguwdxqfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4dXZ0bm51bHlkcmd1d2R4cWZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTQ0NjksImV4cCI6MjA2NTI3MDQ2OX0.8dMIaJNvJyU9XYRzJZjzM5oGgcIz2caOi208a_ZGefw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);